[package]
name = "md-todo"
license = "MIT"
version = "0.1.0"
edition = "2021"
description = "Work with todos in markdown files."
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
